# docker-compose.yml
version: '3.9'
services:
  db:
    image: postgres:14
    container_name: multi_tenant_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myappointmentsdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_booking:/var/lib/postgresql/data

volumes:
  postgres_data_booking:
